<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="showcameras.xsl" ?>
<!--
	License: CC-BY-SA 3.0

	This work is licensed under a
	Creative Commons Attribution-ShareAlike 3.0 Unported License.

	See more at:
	http://creativecommons.org/licenses/by-sa/3.0/
-->

<!DOCTYPE Cameras [
<!ELEMENT BlackAreas ( Vertical*, Horizontal* ) >

<!ELEMENT Camera ( CFA?, CFA2?, Crop, Sensor+, BlackAreas?, Aliases?, Hints?, ID? ) >
<!ATTLIST Camera make CDATA #REQUIRED >
<!ATTLIST Camera model CDATA #REQUIRED >
<!ATTLIST Camera supported CDATA #IMPLIED >
<!ATTLIST Camera mode CDATA #IMPLIED >
<!ATTLIST Camera decoder_version CDATA #IMPLIED >

<!ELEMENT Cameras ( Camera+ ) >
<!ATTLIST Cameras version CDATA #IMPLIED >

<!ELEMENT CFA ( Color+ ) >
<!ATTLIST CFA height NMTOKEN #REQUIRED >
<!ATTLIST CFA width NMTOKEN #REQUIRED >

<!ELEMENT CFA2 ( Color*, ColorRow* ) >
<!ATTLIST CFA2 height NMTOKEN #REQUIRED >
<!ATTLIST CFA2 width NMTOKEN #REQUIRED >

<!ELEMENT Color ( #PCDATA ) >
<!ATTLIST Color x NMTOKEN #REQUIRED >
<!ATTLIST Color y NMTOKEN #REQUIRED >

<!ELEMENT ColorRow ( #PCDATA ) >
<!ATTLIST ColorRow y NMTOKEN #REQUIRED >

<!ELEMENT Crop EMPTY >
<!ATTLIST Crop height NMTOKEN #REQUIRED >
<!ATTLIST Crop width NMTOKEN #REQUIRED >
<!ATTLIST Crop x NMTOKEN #REQUIRED >
<!ATTLIST Crop y NMTOKEN #REQUIRED >

<!ELEMENT Horizontal EMPTY >
<!ATTLIST Horizontal height NMTOKEN #REQUIRED >
<!ATTLIST Horizontal y NMTOKEN #REQUIRED >

<!ELEMENT Sensor EMPTY >
<!ATTLIST Sensor white NMTOKEN #REQUIRED >
<!ATTLIST Sensor black NMTOKEN #REQUIRED >
<!ATTLIST Sensor black_colors NMTOKEN #IMPLIED >
<!ATTLIST Sensor iso_list NMTOKENS #IMPLIED >
<!ATTLIST Sensor iso_min NMTOKEN #IMPLIED >
<!ATTLIST Sensor iso_max NMTOKEN #IMPLIED >

<!ELEMENT Vertical EMPTY >
<!ATTLIST Vertical width NMTOKEN #REQUIRED >
<!ATTLIST Vertical x NMTOKEN #REQUIRED >

<!ELEMENT Hints ( Hint+ ) >
<!ELEMENT Hint EMPTY >
<!ATTLIST Hint name CDATA #REQUIRED >
<!ATTLIST Hint value CDATA #REQUIRED >

<!ELEMENT Aliases ( Alias+ ) >
<!ATTLIST Alias id CDATA #IMPLIED >
<!ELEMENT Alias (#PCDATA) >

<!ELEMENT ID (#PCDATA) >
<!ATTLIST Camera make CDATA #REQUIRED >
<!ATTLIST Camera model CDATA #REQUIRED >
]>

<Cameras>
	<Camera make="ARRI" model="ALEXA">
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">RED</Color>
			<Color x="0" y="1">BLUE</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="4095"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 100D">
		<ID make="Canon" model="EOS 100D">Canon EOS 100D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="52" width="0" height="0"/>
		<Sensor black="0" white="16383"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="8" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel SL1">Canon EOS REBEL SL1</Alias>
			<Alias id="EOS Kiss X7">Canon EOS Kiss X7</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 300D DIGITAL">
		<ID make="Canon" model="EOS 300D">Canon EOS 300D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="64" y="12" width="0" height="0"/>
		<Sensor black="124" white="4000"/>
		<BlackAreas>
			<Vertical x="0" width="60"/>
			<Horizontal y="0" height="10"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Digital Rebel">Canon EOS DIGITAL REBEL</Alias>
			<Alias id="EOS Kiss Digital">Canon EOS Kiss Digital</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS D30">
		<ID make="Canon" model="EOS D30">Canon EOS D30</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="48" y="6" width="0" height="-2"/>
		<Sensor black="126" white="4095"/>
		<BlackAreas>
			<Vertical x="0" width="46"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS D60">
		<ID make="Canon" model="EOS D60">Canon EOS D60</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="64" y="12" width="0" height="0"/>
		<Sensor black="127" white="4000"/>
		<BlackAreas>
			<Vertical x="0" width="60"/>
			<Horizontal y="0" height="10"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 10D">
		<ID make="Canon" model="EOS 10D">Canon EOS 10D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="64" y="12" width="0" height="0"/>
		<Sensor black="127" white="4000"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 20D">
		<ID make="Canon" model="EOS 20D">Canon EOS 20D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="74" y="12" width="3522" height="2348"/>
		<Sensor black="126" white="4095"/>
		<Hints>
			<Hint name="wb_offset" value="50"/>
		</Hints>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="2" height="8"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 30D">
		<ID make="Canon" model="EOS 30D">Canon EOS 30D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="74" y="12" width="3522" height="2348"/>
		<Sensor black="127" white="3398"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="2" height="8"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 350D DIGITAL">
		<ID make="Canon" model="EOS 350D">Canon EOS 350D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="42" y="14" width="3474" height="2314"/>
		<Sensor black="255" white="4095"/>
		<Hints>
			<Hint name="wb_offset" value="50"/>
		</Hints>
		<BlackAreas>
			<Vertical x="0" width="40"/>
			<Horizontal y="0" height="12"/>
		</BlackAreas>
		<Aliases>
			<Alias id="Digital Rebel XT">Canon EOS DIGITAL REBEL XT</Alias>
			<Alias id="Kiss Digital N">Canon EOS Kiss Digital N</Alias>
			<Alias id="EOS 350D">Canon EOS 350D</Alias>
			<Alias id="EOS 350D">Canon EOS 350D Digital</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 40D" decoder_version="2">
		<ID make="Canon" model="EOS 40D">Canon EOS 40D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="30" y="18" width="3908" height="2602"/>
		<Sensor black="1021" white="13600"/>
		<BlackAreas>
			<Vertical x="0" width="28"/>
			<Horizontal y="4" height="12"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 40D" mode="sRaw1">
		<ID make="Canon" model="EOS 40D">Canon EOS 40D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="65535"/>
		<Hints>
			<Hint name="sraw_40d" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 40D" mode="sRaw2">
		<ID make="Canon" model="EOS 40D">Canon EOS 40D</ID>
		<Crop x="0" y="0" width="1944" height="1296"/>
		<Sensor black="0" white="65535"/>
		<Hints>
			<Hint name="sraw_40d" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 450D">
		<ID make="Canon" model="EOS 450D">Canon EOS 450D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="22" y="18" width="4290" height="2856"/>
		<Sensor black="1020" white="14500"/>
		<Aliases>
			<Alias id="Digital Rebel XSi">Canon EOS DIGITAL REBEL XSi</Alias>
			<Alias id="Kiss Digital X2">Canon EOS Kiss Digital X2</Alias>
			<Alias id="Kiss X2">Canon EOS Kiss X2</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 50D" decoder_version="1">
		<ID make="Canon" model="EOS 50D">Canon EOS 50D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="64" y="52" width="4752" height="3158"/>
		<Sensor black="1020" white="13653"/>
		<BlackAreas>
			<Vertical x="0" width="60"/>
			<Horizontal y="2" height="46"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 50D" mode="sRaw1">
		<ID make="Canon" model="EOS 50D">Canon EOS 50D</ID>
		<Crop x="0" y="0" width="3272" height="2178"/>
		<Sensor black="0" white="53000"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 50D" mode="sRaw2">
		<ID make="Canon" model="EOS 50D">Canon EOS 50D</ID>
		<Crop x="0" y="0" width="2376" height="1584"/>
		<Sensor black="0" white="53000"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 60D" decoder_version="1">
		<ID make="Canon" model="EOS 60D">Canon EOS 60D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="146" y="54" width="0" height="0"/>
		<Sensor black="2026" white="14200"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="46"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 60D" mode="sRaw1">
		<ID make="Canon" model="EOS 60D">Canon EOS 60D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="65535"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 60D" mode="sRaw2">
		<ID make="Canon" model="EOS 60D">Canon EOS 60D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="65535"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 70D" decoder_version="1">
		<ID make="Canon" model="EOS 70D">Canon EOS 70D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="38" width="0" height="0"/>
		<Sensor black="2026" white="13653" iso_min="0" iso_max="199"/>
		<Sensor black="2026" white="16383" iso_min="6400" iso_max="25600"/>
		<Sensor black="2026" white="15387"/>
		<BlackAreas>
			<Vertical x="0" width="72"/>
			<Horizontal y="0" height="38"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 70D" mode="sRaw1">
		<ID make="Canon" model="EOS 70D">Canon EOS 70D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="53000"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 70D" mode="sRaw2">
		<ID make="Canon" model="EOS 70D">Canon EOS 70D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="53000"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 700D">
		<ID make="Canon" model="EOS 700D">Canon EOS 700D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="52" width="0" height="0"/>
		<Sensor black="2026" white="13584" iso_min="0" iso_max = "199"/>
		<Sensor black="2026" white="16383" iso_min="6400" iso_max = "25600"/>
		<Sensor black="2026" white="15304"/>
		<BlackAreas>
			<Vertical x="0" width="70"/>
			<Horizontal y="4" height="50"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T5i">Canon EOS REBEL T5i</Alias>
			<Alias id="EOS Kiss X7i">Canon EOS Kiss X7i</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 750D">
		<ID make="Canon" model="EOS 750D">Canon EOS 750D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="34" width="0" height="0"/>
		<Sensor black="2047" white="11765" iso_min="0" iso_max = "199"/>
		<Sensor black="2047" white="14580"/>
		<Aliases>
			<Alias id="EOS Rebel T6i">Canon EOS Rebel T6i</Alias>
			<Alias id="EOS Kiss X8i">Canon EOS Kiss X8i</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 760D">
		<ID make="Canon" model="EOS 760D">Canon EOS 760D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="34" width="0" height="0"/>
		<Sensor black="2047" white="11765" iso_min="0" iso_max = "199"/>
		<Sensor black="2047" white="14580"/>
		<Aliases>
			<Alias id="EOS Rebel T6s">Canon EOS Rebel T6s</Alias>
			<Alias id="EOS 8000D">Canon EOS 8000D</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 500D">
		<ID make="Canon" model="EOS 500D">Canon EOS 500D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="62" y="30" width="4722" height="3142"/>
		<Sensor black="1020" white="16000"/>
		<BlackAreas>
			<Vertical x="0" width="56"/>
			<Horizontal y="2" height="22"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T1i">Canon EOS REBEL T1i</Alias>
			<Alias id="EOS Kiss X3">Canon EOS Kiss X3</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 550D">
		<ID make="Canon" model="EOS 550D">Canon EOS 550D</ID>
		<CFA width="2" height="2">
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="1">GREEN</Color>
			<Color x="0" y="1">RED</Color>
		</CFA>
		<Crop x="148" y="54" width="0" height="0"/>
		<Sensor black="2048" white="15831"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T2i">Canon EOS REBEL T2i</Alias>
			<Alias id="EOS Kiss X4">Canon EOS Kiss X4</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 600D">
		<ID make="Canon" model="EOS 600D">Canon EOS 600D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="146" y="54" width="0" height="0"/>
		<Sensor black="2026" white="13584" iso_min="0" iso_max = "199"/>
		<Sensor black="2026" white="15304"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T3i">Canon EOS REBEL T3i</Alias>
			<Alias id="EOS Kiss X5">Canon EOS Kiss X5</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 650D">
		<ID make="Canon" model="EOS 650D">Canon EOS 650D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="76" y="56" width="0" height="0"/>
		<Sensor black="2026" white="13584" iso_min="0" iso_max = "199"/>
		<Sensor black="2026" white="15304"/>
		<BlackAreas>
			<Vertical x="0" width="70"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T4i">Canon EOS REBEL T4i</Alias>
			<Alias id="EOS Kiss X6i">Canon EOS Kiss X6i</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D">
		<ID make="Canon" model="EOS 5D">Canon EOS 5D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="90" y="34" width="4386" height="2920"/>
		<Sensor black="127" white="3692"/>
		<BlackAreas>
			<Vertical x="0" width="88"/>
			<Horizontal y="2" height="30"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark II" decoder_version="1">
		<ID make="Canon" model="EOS 5D Mark II">Canon EOS 5D Mark II</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="158" y="51" width="5634" height="3753"/>
		<Sensor black="1024" white="12995" iso_list="160 320 640 1250"/>
		<Sensor black="1024" white="15950"/>
		<BlackAreas>
			<Vertical x="0" width="156"/>
			<Horizontal y="2" height="48"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark II" mode="sRaw1">
		<ID make="Canon" model="EOS 5D Mark II">Canon EOS 5D Mark II</ID>
		<Crop x="0" y="0" width="3872" height="2574"/>
		<Sensor black="0" white="57200" iso_list="160 320 640 1250"/>
		<Sensor black="0" white="64948"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark II" mode="sRaw2">
		<ID make="Canon" model="EOS 5D Mark II">Canon EOS 5D Mark II</ID>
		<Crop x="0" y="0" width="2808" height="1872"/>
		<Sensor black="0" white="57200" iso_list="160 320 640 1250"/>
		<Sensor black="0" white="64948"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark III" decoder_version="2">
		<ID make="Canon" model="EOS 5D Mark III">Canon EOS 5D Mark III</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="124" y="82" width="-2" height="0"/>
		<Sensor black="2060" white="16383"/>
		<Sensor black="2060" white="15700" iso_list="400 500 1600"/>
		<Sensor black="2060" white="15200" iso_list="100 125 200 250 800 2000"/>
		<Sensor black="2060" white="15100" iso_list="2500 10000"/>
		<Sensor black="2060" white="13700" iso_list="160 320 1250"/>
		<Sensor black="2060" white="14200" iso_list="640 5000"/>
		<BlackAreas>
			<Vertical x="0" width="120"/>
			<Horizontal y="2" height="78"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark III" mode="sRaw1">
		<ID make="Canon" model="EOS 5D Mark III">Canon EOS 5D Mark III</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="44112" iso_list="160 320 640 1250 2500 5000 10000"/>
		<Sensor black="0" white="50300" iso_list="100 20000"/>
		<Sensor black="0" white="55128" iso_list="25600 51200 65535"/>
		<Sensor black="0" white="53220"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5D Mark III" mode="sRaw2">
		<ID make="Canon" model="EOS 5D Mark III">Canon EOS 5D Mark III</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="44112" iso_list="160 320 640 1250 2500 5000 10000"/>
		<Sensor black="0" white="51300" iso_list="250"/>
		<Sensor black="0" white="55028" iso_list="25600 51200 65535"/>
		<Sensor black="0" white="53000"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5DS" decoder_version="6">
		<ID make="Canon" model="EOS 5DS">Canon EOS 5DS</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="160" y="64" width="-2" height="0"/>
		<Sensor black="2048" white="15181"/>
		<Sensor black="2048" white="14466" iso_list="50 100"/>
		<BlackAreas>
			<Vertical x="0" width="150"/>
			<Horizontal y="2" height="60"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 5DS R" decoder_version="6">
		<ID make="Canon" model="EOS 5DS R">Canon EOS 5DS R</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="160" y="64" width="-2" height="0"/>
		<Sensor black="2048" white="15181"/>
		<Sensor black="2048" white="14466" iso_list="50 100"/>
		<BlackAreas>
			<Vertical x="0" width="150"/>
			<Horizontal y="2" height="60"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 6D" decoder_version="2">
		<ID make="Canon" model="EOS 6D">Canon EOS 6D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="74" y="40" width="0" height="-2"/>
		<Sensor black="2048" white="16383"/>
		<BlackAreas>
			<Vertical x="0" width="68"/>
			<Horizontal y="2" height="36"/>
		</BlackAreas>
	</Camera>
	<!---Guess -->
	<Camera make="Canon" model="Canon EOS 6D" mode="sRaw1" decoder_version="3">
		<ID make="Canon" model="EOS 6D">Canon EOS 6D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="48664"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<!---Guess -->
	<Camera make="Canon" model="Canon EOS 6D" mode="sRaw2">
		<ID make="Canon" model="EOS 6D">Canon EOS 6D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="48664"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 7D" decoder_version="1">
		<ID make="Canon" model="EOS 7D">Canon EOS 7D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="158" y="52" width="5202" height="3464"/>
		<Sensor black="1025" white="8150" iso_min="12800" iso_max="12800"/>
		<Sensor black="2050" white="16300"/>
		<BlackAreas>
			<Vertical x="8" width="156"/>
			<Horizontal y="32" height="18"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 7D" mode="sRaw1">
		<ID make="Canon" model="EOS 7D">Canon EOS 7D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="44200" iso_list="100 125 160 320 640 1250"/>
		<Sensor black="0" white="54000"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 7D" mode="sRaw2">
		<ID make="Canon" model="EOS 7D">Canon EOS 7D</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="44200" iso_list="100 125 160 320 640 1250"/>
		<Sensor black="0" white="54000"/>
	</Camera>
	<Camera make="Canon" model="Canon EOS 7D Mark II">
		<ID make="Canon" model="EOS 7D Mark II">Canon EOS 7D Mark II</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="38" width="0" height="0"/>
		<Sensor black="2047" white="13400" iso_list="100 125 160 200 250 320"/>
		<Sensor black="2047" white="15100"/>
		<BlackAreas>
			<Vertical x="4" width="64"/>
			<Horizontal y="24" height="8"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS 7D Mark II" mode="sRaw1">
		<ID make="Canon" model="EOS 7D Mark II">Canon EOS 7D Mark II</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="65535"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 7D Mark II" mode="sRaw2">
		<ID make="Canon" model="EOS 7D Mark II">Canon EOS 7D Mark II</ID>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="65535"/>
		<Hints>
			<Hint name="sraw_new" value=""/>
			<Hint name="invert_sraw_wb" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS 1000D">
		<ID make="Canon" model="EOS 1000D">Canon EOS 1000D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="42" y="18" width="3906" height="2602"/>
		<Sensor black="255" white="3650" iso_min="0" iso_max="199"/>
		<Sensor black="255" white="4036"/>
		<BlackAreas>
			<Vertical x="0" width="41"/>
			<Horizontal y="2" height="14"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Digital Rebel XS">Canon EOS DIGITAL REBEL XS</Alias>
			<Alias id="EOS Kiss Digital F">Canon EOS Kiss Digital F</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 1100D">
		<ID make="Canon" model="EOS 1100D">Canon EOS 1100D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="64" y="20" width="0" height="0"/>
		<Sensor black="2036" white="15500"/>
		<BlackAreas>
			<Vertical x="0" width="58"/>
			<Horizontal y="4" height="12"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T3">Canon EOS REBEL T3</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 1200D">
		<ID make="Canon" model="EOS 1200D">Canon EOS 1200D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="146" y="54" width="0" height="0"/>
		<Sensor black="2046" white="12279" iso_min="0" iso_max = "199"/>
		<Sensor black="2046" white="15000"/>
		<BlackAreas>
			<Vertical x="0" width="140"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Rebel T5">Canon EOS REBEL T5</Alias>
			<Alias id="EOS Kiss X70">Canon EOS Kiss X70</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS 400D DIGITAL">
		<ID make="Canon" model="EOS 400D">Canon EOS 400D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="42" y="18" width="3906" height="2602"/>
		<Sensor black="255" white="3726"/>
		<BlackAreas>
			<Vertical x="0" width="40"/>
			<Horizontal y="4" height="12"/>
		</BlackAreas>
		<Aliases>
			<Alias id="EOS Digital Rebel XTi">Canon EOS DIGITAL REBEL XTi</Alias>
			<Alias id="EOS Kiss Digital X">Canon EOS Kiss Digital X</Alias>
		</Aliases>
	</Camera>
	<Camera make="Canon" model="Canon EOS M">
		<ID make="Canon" model="EOS M">Canon EOS M</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="76" y="56" width="0" height="0"/>
		<Sensor black="2026" white="13584" iso_min="0" iso_max = "199"/>
		<Sensor black="2026" white="15304"/>
		<BlackAreas>
			<Vertical x="0" width="70"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS M2">
		<ID make="Canon" model="EOS M2">Canon EOS M2</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="52" width="0" height="0"/>
		<Sensor black="2026" white="13584" iso_min="0" iso_max = "199"/>
		<Sensor black="2026" white="15304"/>
		<BlackAreas>
			<Vertical x="0" width="70"/>
			<Horizontal y="4" height="44"/>
		</BlackAreas>
	</Camera>
	<Camera make="Canon" model="Canon EOS M3">
		<ID make="Canon" model="EOS M3">Canon EOS M3</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="72" y="34" width="0" height="0"/>
		<Sensor black="2048" white="16000"/>
		<BlackAreas>
			<Vertical x="2" width="68"/>
			<Horizontal y="2" height="30"/>
		</BlackAreas>
		<Hints>
			<Hint name="wb_offset" value="142"/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS-1D" decoder_version="5">
		<ID make="Canon" model="EOS-1D">Canon EOS-1D</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">RED</Color>
			<Color x="0" y="1">BLUE</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="3588"/>
		<Hints>
			<Hint name="old_format" value=""/>
			<Hint name="double_line_ljpeg" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS-1DS" decoder_version="5">
		<ID make="Canon" model="EOS-1Ds">Canon EOS-1Ds</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">RED</Color>
			<Color x="0" y="1">BLUE</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="3500"/>
		<Hints>
			<Hint name="old_format" value=""/>
			<Hint name="double_line_ljpeg" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="EOS D2000C" decoder_version="5">
		<CFA width="2" height="2">
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">RED</Color>
			<Color x="0" y="1">BLUE</Color>
			<Color x="1" y="1">GREEN</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="96" white="4095"/>
		<Hints>
			<Hint name="old_format" value=""/>
		</Hints>
	</Camera>
	<Camera make="Canon" model="Canon EOS-1D Mark II">
		<ID make="Canon" model="EOS-1D Mark II">Canon EOS-1D Mark II</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="74" y="12" width="3522" height="2348"/>