=== darktable-org/darktable/data/darktableconfig.dtd
<!ELEMENT dtconfiglist (dtconfig)*>
<!ELEMENT dtconfig (name,type,default,capability?,shortdescription?,longdescription?)>
<!ATTLIST dtconfig
	prefs (import|lighttable|darkroom|otherviews|processing|security|cpugpu|storage|misc) #IMPLIED
        section
        (import|session|interface|other|tags|geoloc|slideshow|cpugpu|database|xmp|accel|general|modules|thumbs) #IMPLIED
        dialog (collect|import) #IMPLIED
        ui (yes|no) #IMPLIED
        restart (true|false) #IMPLIED
        capability CDATA #IMPLIED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA|enum)*>
<!ATTLIST type
	min CDATA #IMPLIED
	max CDATA #IMPLIED
    digits CDATA #IMPLIED
	factor CDATA #IMPLIED
><!ELEMENT enum (option)+>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	capability CDATA #IMPLIED
>
<!ELEMENT default (#PCDATA)>
<!ELEMENT shortdescription (#PCDATA)>
<!ELEMENT longdescription (#PCDATA)>

=== darktable-org/darktable/data/darktableconfig.xml
<?xml version="1.0"?>
<!DOCTYPE dtconfiglist SYSTEM "darktableconfig.dtd">
<dtconfiglist>
  <dtconfig>
    <name>bauhaus/scale</name>
    <type>float</type>
    <default>1.4</default>
    <shortdescription>widget scale</shortdescription>
    <longdescription>scaling factor for bauhaus widgets, will affect font size</longdescription>
  </dtconfig>
  <dtconfig>
    <name>database</name>
    <type>string</type>
    <default>library.db</default>
    <shortdescription>database location</shortdescription>
    <longdescription>filename relative to ~/.config/darktable or starting with a slash (needs a restart).</longdescription>
  </dtconfig>
  <dtconfig prefs="gui">
    <name>panel_width</name>
    <type>int</type>
    <default>300</default>
    <shortdescription>width of the side panels in pixels</shortdescription>
    <longdescription> (needs a restart)</longdescription>
  </dtconfig>
  <dtconfig prefs="core">
    <name>cache_memory</name>
    <type>int</type>
    <default>536870912</default>
    <shortdescription>memory in bytes to use for mipmap cache</shortdescription>
    <longdescription> (needs a restart) </longdescription>
  </dtconfig>
  <dtconfig prefs="core">
    <name>worker_threads</name>
    <type>int</type>
    <default>2</default>
    <shortdescription>number of background threads</shortdescription>
    <longdescription>this controls for example how many threads are used to create thumbnails during import. the cache will grow to a maximum of twice this number of full resolution image buffers (needs a restart).</longdescription>
  </dtconfig>
  <dtconfig prefs="core">
    <name>parallel_export</name>
    <type>int</type>
    <default>1</default>
    <shortdescription>export multiple images in parallel</shortdescription>
    <longdescription>set this variable to num_threads if you want multithreaded export to process multiple images at a time. be warned: every thread will need about 1GB of memory. setting this to 1 switches on per-image parallelization.</longdescription>
  </dtconfig>
  <dtconfig prefs="core">
    <name>host_memory_limit</name>
    <type min="500">int</type>
    <default>1500</default>
    <shortdescription>host memory limit (in MB) for tiling</shortdescription>
    <longdescription>this variable controls the maximum amount of memory (in MB) a module may use during image processing. lower values will force memory hungry modules to process image with increasing number of tiles. setting this to 0 will omit any limit. values below 500 will be treated as 500. needs a restart.</longdescription>
  </dtconfig>
  <dtconfig prefs="core">
    <name>singlebuffer_limit</name>
    <type min="2">int</type>
    <default>16</default>
    <shortdescription>minimum amount of memory (in MB) for a single buffer in tiling</shortdescription>
    <longdescription>if set to a positive, non-zero value this variable defines the minimum amount of memory (in MB) that tiling should take for a single image buffer. has precedence over heuristics based on host_memory_limit. needs a restart.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_memory_headroom</name>
    <type>int</type>
    <default>300</default>
    <shortdescription>amount of opencl memory (in MB) which we assume as being reserved for the driver</shortdescription>
    <longdescription>this amount of memory (in MB) will be substracted from total gpu memory in order to calculate the available opencl memory. too low values will lead to out-of-memory situations in opencl processing. too high values will lead to unnecessary tiling (needs a restart).</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_avoid_atomics</name>
    <type>bool</type>
    <default>false</default>
    <shortdescription>do not run opencl kernels which require atomic operations</shortdescription>
    <longdescription>if set to TRUE darktable will not use opencl kernels which contain atomic operations (example bilateral). pixelpipe processing will be done on cpu for the affected modules. useful if your opencl implementation freezes/crashes on atomics or if they are processed with a bad performance.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_number_event_handles</name>
    <type>int</type>
    <default>25</default>
    <shortdescription>the number of opencl event handles darktable can use</shortdescription>
    <longdescription>a positive non-zero integer defines the number of event handles that darktable may have opened on a device. a value of -1 does not pose any restrictions, bearing the risk of hitting the device's resource limits. a value of zero completely prevents the use of event handles.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_async_pixelpipe</name>
    <type>bool</type>
    <default>false</default>
    <shortdescription>run opencl pixelpipe asynchronously</shortdescription>
    <longdescription>if set to TRUE opencl pixelpipe will not be synchronized on a per-module basis. this can improve pixelpipe latency. however, potential opencl errors would be detected late; in such a case the complete pixelpipe needs to be reprocessed instead of only a single module. export pixelpipe will always be run synchronously.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_synch_cache</name>
    <type>bool</type>
    <default>false</default>
    <shortdescription>copy back opencl buffers into pixelpipe cache after each module</shortdescription>
    <longdescription>this brings pixelpipe cache and opencl buffers in synch after each module. on slow GPUs this might improve speed as it avoids reprocessing the whole pixelpipe on every parameter change. on fast GPUs the additional memory transfer overhead will slow down opencl considerably.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_micro_nap</name>
    <type>int</type>
    <default>1000</default>
    <shortdescription>pause opencl processing for this number of microseconds from time to time</shortdescription>
    <longdescription>for slow GPUs this gives your graphics driver some time to breathe to do needed screen updates. can be left at zero for fast devices.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_device_priority</name>
    <type>string</type>
    <default>*/!0,*/*/*</default>
    <shortdescription>priority of OpenCL devices for each pixelpipe type</shortdescription>
    <longdescription>defines priorities on how (multiple) OpenCL devices are allocated to the different types of pixelpipe (full, preview, export, thumbnail). for more details visit our usermanual. needs a restart.</longdescription>
  </dtconfig>
  <dtconfig prefs="gui">
    <name>never_use_embedded_thumb</name>
    <type>bool</type>
    <default>false</default>
    <shortdescription>don't use embedded preview jpeg but half-size raw</shortdescription>
    <longdescription>check this option to not use the embedded jpeg from the raw file but process the raw data. this is slower but gives you color managed thumbnails.</longdescription>
  </dtconfig>
  <dtconfig prefs="core">
    <name>write_sidecar_files</name>
    <type>bool</type>
    <default>true</default>
    <shortdescription>write sidecar file for each image</shortdescription>
    <longdescription>these redundant files can later be re-imported into a different database, preserving your changes to the image.</longdescription>
  </dtconfig>
  <dtconfig prefs="core" capability="opencl">
    <name>opencl</name>
    <type>bool</type>
    <default>true</default>
    <shortdescription>activate opencl support</shortdescription>
    <longdescription>if found, use opencl runtime on your system for improved processing speed. can be switched on and off at any time.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_library</name>
    <type>string</type>
    <default/>
    <shortdescription>system library with opencl runtime</shortdescription>
    <longdescription>opencl runtime library is normally detected automatically by darktable. if your opencl runtime is at an unusual place and cannot be detected, enter the full pathname here. leave empty for default behavior.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_memory_requirement</name>
    <type>int</type>
    <default>768</default>
    <shortdescription>minmum amount of GPU memory (MB) required to activate opencl</shortdescription>
    <longdescription>opencl will only be activated if your graphics card has at least this amount of memory. reducing the value will allow cards with less GPU memory to be used - but at the risk of lower system stability and occasional crashes. values below 200 will be treated as 200.</longdescription>
  </dtconfig>
  <dtconfig>
    <name>opencl_size_roundup</name>
    <type>int</type>
    <default>16</default>
    <shortdescription>round opencl work group sizes to a multiple of</shortdescription>
    <longdescription>in opencl processing round width/height of global work groups to a multiple of this value. reasonable values are powers of 2. this parameter can have high impact on opencl performance.</longdescription>
  </dtconfig>
  <dtconfig prefs="gui">
    <name>ask_before_remove</name>
    <type>bool</type>
    <default>true</default>
    <shortdescription>ask before removing images from database</shortdescription>
    <longdescription>always ask the user before any image is removed from db.</longdescription>
  </dtconfig>
  <dtconfig prefs="gui">
    <name>ask_before_delete</name>
    <type>bool</type>
    <default>true</default>
    <shortdescription>ask before erasing images from disk</shortdescription>
    <longdescription>always ask the user before any image file is deleted.</longdescription>
  </dtconfig>
  <dtconfig prefs="gui">
    <name>ask_before_move</name>
    <type>bool</type>
    <default>true</default>
    <shortdescription>ask before moving images from film roll folder</shortdescription>
    <longdescription>always ask the user before any image file is moved.</longdescription>
  </dtconfig>
